- name: Initialize Kubernetes master
  command: kubeadm init --pod-network-cidr=192.168.0.0/16 --cri-socket unix:///var/run/docker.sock
  register: kubeadm_init_output
- name: Create .kube directory
  become_user: "{{ ansible_user }}"
  file:
    path: "{{ ansible_user_dir }}/.kube"
    state: directory
    mode: '0755'
- name: Copy kubeconfig to user's home directory
  become_user: "{{ ansible_user }}"
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_user_dir }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user }}"
- name: Install Calico network plugin
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
- name: get join command
  command: kubeadm token create --print-join-command
  register: join_command
- set_fact:
    join_cmd: "{{ join_command.stdout }}"
