version: "3.8"
services:
  db:
    image: mariadb
    container_name: tracker_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: tracker
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: tracker_app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - db

volumes:
  mariadb_data: