---
      - name: "Create Required Databases for Application {{ app_name }}"
        mysql_db: 
          name: 
            - "{{ mysql_db_1_name }}" 
            - "{{ mysql_db_2_name }}" 
            - "{{ mysql_db_3_name }}" 
            - "{{ mysql_db_4_name }}" 
          state: present 
          login_user: root 
          login_password: "{{ mysql_root_password }}"
          
      - name: Copy required DB Tables export file on the the server
        copy:
          src: "{{ item }}"
          dest: /tmp/
        loop: 
          - add_remote_access.sql
          - table_admin_data.sql
          - table_admin_accounts.sql
          - table_menu.sql
          - table_settings.sql
          - table_users.sql
          - table_token.sql
          - table_invest_temp.sql
          - view_OTP.sql
          
      - name: Update Remote Access user info
        shell: |
          sed -i 's/REMOTEUSER/{{ mysql_svc_user }}/g' /tmp/add_remote_access.sql;
          sed -i 's/REMOTEUSER/{{ mysql_svc_user }}/g' /tmp/view_OTP.sql;
          sed -i 's/REMUSERPASS/{{ mysql_svc_pass }}/g' /tmp/add_remote_access.sql
          sed -i 's/SETTINGSDB/{{ mysql_db_3_name }}/g' /tmp/view_OTP.sql;
      - name: Create service account for Application access
        mysql_db:
          name: mysql
          state: import
          target:  /tmp/add_remote_access.sql
          login_user: root
          login_password: "{{ mysql_root_password }}"
      - name: Create the Data Table for Admin user in the Database
        mysql_db:
          name: "{{ mysql_db_1_name }}" 
          state: import
          target:  /tmp/table_admin_data.sql
          login_user: root
          login_password: "{{ mysql_root_password }}"
      - name: Create the Accounts Table for Admin user in the Database
        mysql_db:
          name: "{{ mysql_db_2_name }}" 
          state: import
          target:  /tmp/table_admin_accounts.sql
          login_user: root
          login_password: "{{ mysql_root_password }}"
      - name: Create the Investments Table template in the Database
        mysql_db:
          name: "{{ mysql_db_2_name }}" 
          state: import
          target:  /tmp/table_invest_temp.sql
          login_user: root
          login_password: "{{ mysql_root_password }}"
      - name: Create the Dropdown Menu Table Data
        mysql_db:
          name: "{{ mysql_db_4_name }}" 
          state: import
          target:  /tmp/table_menu.sql
          login_user: root
          login_password: "{{ mysql_root_password }}"
      - name: Create the Settings Table in the Database
        mysql_db:
          name: "{{ mysql_db_3_name }}" 
          state: import
          target:  /tmp/table_settings.sql
          login_user: root
          login_password: "{{ mysql_root_password }}"
      - name: Create the Token Table in the Database
        mysql_db:
          name: "{{ mysql_db_3_name }}" 
          state: import
          target:  /tmp/table_token.sql
          login_user: root
          login_password: "{{ mysql_root_password }}"
      - name: Create the OTP View in the Database
        mysql_db:
          name: "{{ mysql_db_3_name }}" 
          state: import
          target:  /tmp/view_OTP.sql
          login_user: root
          login_password: "{{ mysql_root_password }}"
      - name: Create users table and Default user account.
        mysql_db:
          name: "{{ mysql_db_3_name }}" 
          state: import
          target:  /tmp/table_users.sql
          login_user: root
          login_password: "{{ mysql_root_password }}"

      - name: Remove the sql files on remote server
        file:
          dest: /tmp/{{ item }}
          state: absent
        loop: 
          - add_remote_access.sql
          - table_admin_data.sql
          - table_admin_accounts.sql
          - table_menu.sql
          - table_settings.sql
          - table_users.sql
          - table_token.sql
          - table_invest_temp.sql
          - view_OTP.sql