CREATE TABLE IF NOT EXISTS settings (
  `SerialNo` INT(1) NOT NULL AUTO_INCREMENT,
  `Organisation` VARCHAR(20) NOT NULL,
  `Logo` VARCHAR(25) NOT NULL,
  `Application` VARCHAR(20) NOT NULL,
  `Description` VARCHAR(150) NOT NULL,
  `SMTP` VARCHAR(100) NOT NULL,
  `Port` VARCHAR(5) NOT NULL,
  `SMTPUser` VARCHAR(100) NULL,
  `SMTPPass` VARCHAR(100) NOT NULL,
  `SVCEmail` VARCHAR(30) NOT NULL,
  `SVCName` VARCHAR(25) NOT NULL,
  `Debug` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`SerialNo`, `Application`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
