---
  - name: Terminate the instance
    oci_instance:
      id: "{{ instance_id }}"
      state: absent

  - name: Delete the subnet
    oci_subnet:
      id: "{{ instance_subnet_id }}"
      state: absent

  - name: Delete the security list
    oci_security_list:
      id: "{{ instance_security_list_ocid }}"
      state: absent

  - name: Delete the route table
    oci_route_table:
      id: "{{ rt_id }}"
      state: absent

  - name: Delete the Internet Gateway
    oci_internet_gateway:
      id: "{{ ig_id }}"
      state: absent

  - name: Delete the VCN
    oci_vcn:
      vcn_id: "{{ vcn_id }}"
      state: absent
