services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd
      MYSQL_DATABASE: "finance_tracker"
    volumes:
      - mariadb_data:/var/lib/mysql
    #ports:
    #  - "3306:3306"

  app:
    build: .
    env_file:
      - .env
    container_name: expense_tracker_app
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=Passw0rd
      - DB_NAME=finance_tracker
    #restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./AppData/app:/app
    #command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  web:
    image: nginx:latest
    container_name: expense_tracker_web
    ports:
      - "80:80"
    volumes:
      - ./AppData/web:/usr/share/nginx/html
    depends_on:
      - mariadb
      - app

volumes:
  mariadb_data:
