---
  - name: "Deploy HTTP Services"
    hosts: webserver
    become: yes
    tasks:
      - name: "Install Web Service"
        yum:
          name: 
            - yum
            - php
          state: present
