---
- name: Start and enable libvirtd
  ansible.builtin.systemd:
    name: 
      - libvirtd
      - virtqemud
    state: started
    enabled: yes

- name: Start and enable cockpit
  ansible.builtin.systemd:
    name: cockpit
    state: started
    enabled: yes

