---
  - name: Deploy Tracker Application
    copy:
      src: ./AppData
      dest: /root/

  - name: Build the docker image and deploy the containers
    # shell: docker compose up -d
    # args:
    #   chdir: /root/AppData

    community.docker.docker_compose_v2:
      project_src: /root/AppData
      build: always
      state: present
      #restarted: true
