---
- name: Create required directory structure for Code Depolyment
  file:
    name:
      - /app/MariaDB
      - /app/Data
    state: directory

- name: Deploy Required containers on Docker Host
  community.docker.docker_compose_v2:
    project_name: Tracker
    definition:
      services:
        db01:
          container_name: Tracker_db01
          image: mariadb/server
          restart: always
          volumes:
            - mariadb_data:/var/lib/mysql
          ports:
            - 3306:3306
        app01:
          container_name: Tracker_app01
          image: 
          restart: always
          volumes:
            - app_data:/app
          ports:
            - 8000:8000
      volumes:
        mariadb_data: 
          driver_options:
            type: btrfs
            device: /app/MariaDB
        app_data:
          driver_options:
            type: btrfs
            device: /app/Data
