---
  - name: Destroy a Server in QEMU
    hosts: dell
    become: yes
    vars_files:
      - vars.yml
    vars:
      server_name: "{{ NEWSERVERNAME }}"
    tasks:
      - name: Check if VM present
        shell: "virsh list --all | grep {{ server_name }} | awk '{print $2}'"
        register: vm_available
      - name: Destroy the new server
        virt:
          name: "{{ server_name }}"
          state: shutdown
        when: vm_available.stdout.find("{{ server_name }}") != -1
      - name: Delete the server
        command: "virsh undefine {{ server_name }}"
        when: vm_available.stdout.find("{{ server_name }}") != -1
      - name: Remove the server Disk File
        command: "rm -rf /var/lib/libvirt/images/{{ server_name }}.qcow*"
        when: vm_available.stdout.find("{{ server_name }}") != -1
      