FROM rockylinux:9.3

WORKDIR /Python/WebApps/

RUN dnf install -y python3 python3-pip

COPY AppData/requirements.txt /Python/requirements/

RUN pip3 install -r /Python/requirements/requirements.txt

EXPOSE 8000

ENTRYPOINT uvicorn main:app --reload --host 0.0.0.0 >> /Python/WebApps/Logs/server.log
