FROM rockylinux:9.3

RUN echo "[mongodb-org-7.0] " > /etc/yum.repos.d/mongodb-org-7.0.repo
RUN echo "name=MongoDB Repository " >> /etc/yum.repos.d/mongodb-org-7.0.repo
RUN echo "baseurl=https://repo.mongodb.org/yum/redhat/9/mongodb-org/7.0/x86_64/ " >> /etc/yum.repos.d/mongodb-org-7.0.repo
RUN echo "gpgcheck=1 " >> /etc/yum.repos.d/mongodb-org-7.0.repo
RUN echo "enabled=1 " >> /etc/yum.repos.d/mongodb-org-7.0.repo
RUN echo "gpgkey=https://pgp.mongodb.com/server-7.0.asc" >> /etc/yum.repos.d/mongodb-org-7.0.repo

RUN yum install -y mongodb-org


RUN echo '#!/bin/bash' > /usr/local/bin/docker-entrypoint.sh
RUN echo 'set -e' >> /usr/local/bin/docker-entrypoint.sh
RUN echo 'if [ "$(ls -A /docker-entrypoint-initdb.d/)" ]; then' >> /usr/local/bin/docker-entrypoint.sh
RUN echo 'for f in /docker-entrypoint-initdb.d/*; do' >> /usr/local/bin/docker-entrypoint.sh
RUN echo 'case "$f" in' >> /usr/local/bin/docker-entrypoint.sh
RUN echo '*.sh) echo "$0: running $f"; . "$f" ;;' >> /usr/local/bin/docker-entrypoint.sh
RUN echo '*.js) echo "$0: running $f with mongo"; mongo "$f" ;;' >> /usr/local/bin/docker-entrypoint.sh
RUN echo '*)    echo "$0: ignoring $f" ;;' >> /usr/local/bin/docker-entrypoint.sh
RUN echo 'esac' >> /usr/local/bin/docker-entrypoint.sh
RUN echo 'done' >> /usr/local/bin/docker-entrypoint.sh
RUN echo 'fi' >> /usr/local/bin/docker-entrypoint.sh
RUN echo 'esac' >> /usr/local/bin/docker-entrypoint.sh
RUN echo 'exec "$@"' >> /usr/local/bin/docker-entrypoint.sh


RUN mkdir -p /data /var/log/mongodb /docker-entrypoint-initdb.d && \
    chown -R mongod:mongod /data /var/log/mongodb /docker-entrypoint-initdb.d

RUN chmod +x /usr/local/bin/docker-entrypoint.sh
RUN chmod -R 777 /docker-entrypoint-initdb.d/

EXPOSE 27017

ENTRYPOINT ["/docker-entrypoint-initdb.d/init-script.js"]

CMD ["mongod", "--dbpath", "/data", "--logpath", "/var/log/mongodb/mongod.log", "--bind_ip_all"]

#ENTRYPOINT uvicorn main:app --reload --host 0.0.0.0 >> /Python/WebApps/Logs/server.log
