---
# Tasks file for Installing Docker
- name: Enable DNF Plugin core
  become: true
  dnf:
    name: dnf-plugins-core
    state: present
- name: Enable Docker repository
  become: true
  command: dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
  args:
      creates: /etc/yum.repos.d/docker-ce.repo
- name: Ensure Docker is installed
  become: true
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - python3-pip
    state: present
- name: Start Docker service
  become: true
  service:
    name: docker
    state: started
    enabled: yes
- name: Install Python docker module
  pip:
    name:
      - docker
      - docker-compose
    state: present
- name: Add user to docker gorup
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
