---
- name: Deploy AWX Server
  hosts: lab
  become: yes
  become_user: cloud_user   ## Added for Testing purpose ###
  vars:
    ansible_ssh_common_args: "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  tasks:

    - name: Install MiniKube 
      ansible.builtin.get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/bin/minikube
        mode: 0755

    - name: Check minikube status
      command: minikube status --output=json
      register: minikube_status_json
      changed_when: false
      ignore_errors: true

    - name: Start the minikube cluster if not running
      shell: minikube start --addons=ingress --driver=docker
      when: >
        ('not found' in minikube_status_json.stdout) or
        (minikube_status_json.stdout | from_json).Host != "Running" or
        (minikube_status_json.stdout | from_json).Kubelet != "Running" or
        (minikube_status_json.stdout | from_json).APIServer != "Running"
  
    - name: Create awx directory
      file:
        name: ~/awx
        state: directory  

    - name: Create AWX namespace
      kubernetes.core.k8s:
        name: awx
        api_version: v1
        kind: Namespace
        state: present

    - name: Change the namespace to awx
      shell: minikube kubectl -- config set-context --current --namespace=awx

    - name: Create awx.yaml for AWX Operator
      copy:
        dest: "~/awx/awx.yaml"
        content: |
          ---
          apiVersion: awx.ansible.com/v1beta1
          kind: AWX
          metadata:
           name: awx
          spec: 
            service_type: nodeport

    - name: Create kustomization.yaml for AWX Operato
      copy:
        dest: "~/awx/kustomization.yaml"
        content: |
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          resources:
            - github.com/ansible/awx-operator/config/default?ref=2.5.3
            - awx.yaml
          images:
            - name: quay.io/ansible/awx-operator
              newTag: 2.5.3
          namespace: awx

    - name: Apply Kustomization to deploy AWX Operator
      command: minikube kubectl -- apply -k ~/awx

    - name: Wait for AWX service to be accessible
      pause:
        seconds: 59

    - name: Start AWX service on Minikube
      shell: minikube service awx-operator-controller-manager-metrics-service -n awx

        #    - name: Open port for accessing the AWX from internet
        #      shell: minikube kubectl -- port-forwarding svc/awx-service --address 0.0.0.0 8080:80 &> /dev/null &
        #      register: AWX_URL

    - name: Open port for accessing the AWX from internet
      shell: |
          nohup minikube kubectl -- port-forward svc/awx-service --address 0.0.0.0 8080:80 > /tmp/awx_port_forward.log 2>&1 &
      async: 10
      poll: 0

    - name: Wait for AWX service to be accessible
      pause:
        seconds: 5

    - name: Get Minikube IP
      command: minikube ip
      register: minikube_ip
      changed_when: false

    - name: Display AWX URL
      debug:
        msg: "AWX is accessible at http://{{ minikube_ip.stdout }}:8080"

